### ISSUE TITLE
Searching for user guides does not always work 

### ISSUE THREAD

**Issue by mattab** [matomo-org/developer-documentation#23]
Reproduce:
- Search for `contrib` 
- Expected to see in dropdown the page: http://developer.piwik.org/guides/contributing-to-piwik-core
- Got: no result instead.

Note: it works for almost the same query `contr` finds the results.

**Comment by mattab** [comment]
today we got a report from email:

> 
the search bar on developer.piwik.org is not working for me.  I can type in my query and I hit enter repeatedly and nothing happens.  I'm using Firefox as my browser.

**Comment by Findus23** [comment]
Fixed in https://github.com/Findus23/developer-documentation/commit/760333bcf7b7d9ac809d5c12a4d2f793d74cd6f7

I am currently looking through the code and trying to modernize some parts that weren't touched for a long time: https://github.com/piwik/developer-documentation/compare/master...Findus23:various-improvements
(As I don't have much time at the moment this will take a bit longer)

Typeahead doesn't allow `-1` as the number of items in https://github.com/piwik/developer-documentation/blob/master/app/public/js/app.js#L41, so it broke when there was just one result left and showed nothing

**Comment by mattab** [comment]
Hi @Findus23 maybe you can create a PR with this bug fix only? as soon as we merge PR on this repo, they get deployed to the website live.
